// ... (keep imports)
import { Language } from './types';
import { Camera, FileText, MessageCircle, Home, Flame, Thermometer, Zap, Activity, Heart, Brain, Baby, Stethoscope, Droplets, Wind, Dna, Eye, Smile, Bone, Sun, Pill } from 'lucide-react';

export const TRANSLATIONS = {
  en: {
    appTitle: "MediScan AI",
    appSubtitle: "Your Personal AI Health Assistant",
    home: "Home",
    scan: "Scan",
    chat: "Chat",
    search: "Search",
    uploadTitle: "Scan Prescription or Report",
    uploadDesc: "Upload a prescription to get medicine details, or a medical report for health & diet advice.",
    uploadBtn: "Upload Image",
    cameraBtn: "Use Camera",
    analyzing: "Analyzing document...",
    translating: "Translating...",
    resultsTitle: "Analysis Results",
    noMedicines: "No specific medical data detected. Try a clearer image.",
    chatPlaceholder: "Ask about your health or upload a report...",
    welcomeChat: "Hello! I am your AI health assistant. You can upload a report or prescription here, and I will explain it or give you health advice.",
    disclaimer: "Disclaimer: Information provided is for educational purposes only and not a substitute for professional medical advice.",
    medicineName: "Name",
    dosage: "Dosage",
    frequency: "Frequency",
    purpose: "Purpose",
    instructions: "Instructions",
    warnings: "Warnings",
    askAbout: "Ask about this",
    clear: "Clear",
    send: "Send",
    language: "English",
    reportType: "Document Type",
    findings: "Key Findings",
    dietAllowed: "Foods to Eat",
    dietAvoid: "Foods to Avoid",
    lifestyle: "Lifestyle Advice",
    status: "Status",
    uncertainName: "Uncertain Name / Spelling",
    verifyWithDoctor: "The handwriting was unclear or the name didn't match known drugs. Please verify with a pharmacist.",
    lowConfidence: "Review Needed",
    searchTitle: "Medicine Search",
    searchPlaceholder: "Enter medicine name (e.g. Napa, Seclo)...",
    searchBtn: "Search",
    searching: "Searching...",
    notFound: "Medicine not found.",
    didYouMean: "Did you mean:",
    uses: "Uses / Benefits",
    dosageByAge: "Dosage by Age",
    child: "Children",
    adult: "Adults",
    elderly: "Elderly",
    sideEffects: "Side Effects",
    advantages: "Advantages",
    generic: "Generic Name",
    browseConditions: "Browse by Health Condition",
    popularMedicinesFor: "Popular Medicines for",
    backToCategories: "Back to Categories",
    proTip: "Pro Tip:",
    proTipDesc: "For best accuracy with handwritten prescriptions, ensure good lighting and avoid blur. The AI acts as a pharmacist to reconstruct valid medicine names.",
    parameter: "Parameter",
    value: "Value",
    showingResultsFor: "Showing results for",
    consultDoctor: "Consult Doctor",
    standardDosage: "Standard Dosage",
    useWithCaution: "Use with caution",
    errorGeneric: "Sorry, I encountered an error processing your request. Please try again.",
    errorQuota: "Service is busy (Quota Exceeded). Please try again later.",
    docTypes: {
      PRESCRIPTION: "Prescription",
      REPORT: "Medical Report",
      OTHER: "Other Medical Document"
    }
  },
  bn: {
    appTitle: "মেডিক্স স্ক্যান",
    appSubtitle: "আপনার ব্যক্তিগত এআই স্বাস্থ্য সহকারী",
    home: "হোম",
    scan: "স্ক্যান",
    chat: "চ্যাট",
    search: "ঔষধ খুঁজুন",
    uploadTitle: "প্রেসক্রিপশন বা রিপোর্ট স্ক্যান",
    uploadDesc: "ওষুধের তথ্যের জন্য প্রেসক্রিপশন বা স্বাস্থ্য পরামর্শের জন্য মেডিকেল রিপোর্ট আপলোড করুন।",
    uploadBtn: "ছবি আপলোড",
    cameraBtn: "ক্যামেরা ব্যবহার",
    analyzing: "ডকুমেন্ট বিশ্লেষণ করছে...",
    translating: "অনুবাদ করা হচ্ছে...",
    resultsTitle: "বিশ্লেষণ ফলাফল",
    noMedicines: "কোনো তথ্য পাওয়া যায়নি। পরিষ্কার ছবি দিন।",
    chatPlaceholder: "স্বাস্থ্য সম্পর্কে জিজ্ঞাসা করুন বা রিপোর্ট দিন...",
    welcomeChat: "আসসালামুআলাইকুম! আমি আপনার এআই স্বাস্থ্য সহকারী। আপনি এখানে রিপোর্ট বা প্রেসক্রিপশন আপলোড করতে পারেন, আমি তা বুঝিয়ে বলব।",
    disclaimer: "সতর্কতা: প্রদত্ত তথ্য শুধুমাত্র শিক্ষার উদ্দেশ্যে এবং পেশাদার চিকিৎসা পরামর্শের বিকল্প নয়।",
    medicineName: "নাম",
    dosage: "ডোজ",
    frequency: "সেবনের নিয়ম",
    purpose: "উদ্দেশ্য",
    instructions: "নির্দেশনা",
    warnings: "সতর্কতা",
    askAbout: "এটি সম্পর্কে জানুন",
    clear: "মুছে ফেলুন",
    send: "পাঠান",
    language: "বাংলা",
    reportType: "ডকুমেন্টের ধরন",
    findings: "প্রধান ফলাফল",
    dietAllowed: "যেসব খাবার খাবেন",
    dietAvoid: "যেসব খাবার এড়িয়ে চলবেন",
    lifestyle: "জীবনযাত্রার পরামর্শ",
    status: "অবস্থা",
    uncertainName: "নাম বা বানান অস্পষ্ট",
    verifyWithDoctor: "হাতের লেখা অস্পষ্ট বা ওষুধের নামটি পরিচিত তালিকার সাথে মিলছে না। ফার্মাসিস্টের সাথে যাচাই করুন।",
    lowConfidence: "যাচাই প্রয়োজন",
    searchTitle: "ঔষধ অনুসন্ধান",
    searchPlaceholder: "ঔষধের নাম লিখুন (যেমন: নাপা, সেক্লো)...",
    searchBtn: "খুঁজুন",
    searching: "খোঁজা হচ্ছে...",
    notFound: "ঔষধটি পাওয়া যায়নি।",
    didYouMean: "আপনি কি বোঝাতে চেয়েছেন:",
    uses: "ব্যবহার / উপকারিতা",
    dosageByAge: "বয়স অনুযায়ী মাত্রা",
    child: "শিশু",
    adult: "প্রাপ্তবয়স্ক",
    elderly: "বৃদ্ধ",
    sideEffects: "পার্শ্বপ্রতিক্রিয়া",
    advantages: "সুবিধাসমূহ",
    generic: "জেনেরিক নাম",
    browseConditions: "রোগ অনুযায়ী ঔষধ খুঁজুন",
    popularMedicinesFor: "জনপ্রিয় ঔষধ -",
    backToCategories: "আগের মেনুতে ফিরে যান",
    proTip: "পরামর্শ:",
    proTipDesc: "হাতে লেখা প্রেসক্রিপশন সঠিকভাবে পড়ার জন্য পর্যাপ্ত আলোয় পরিষ্কার ছবি তুলুন। ঘোলা ছবি এড়িয়ে চলুন।",
    parameter: "প্যারামিটার",
    value: "ফলাফল/মান",
    showingResultsFor: "ফলাফল দেখানো হচ্ছে - ",
    consultDoctor: "ডাক্তারের পরামর্শ নিন",
    standardDosage: "সাধারণ মাত্রা",
    useWithCaution: "সতর্কতা অবলম্বন করুন",
    errorGeneric: "দুঃখিত, অনুরোধটি প্রক্রিয়া করতে সমস্যা হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
    errorQuota: "সেবাটি বর্তমানে ব্যস্ত আছে (কোটা শেষ)। অনুগ্রহ করে কিছুক্ষণ পর চেষ্টা করুন।",
    docTypes: {
      PRESCRIPTION: "প্রেসক্রিপশন",
      REPORT: "মেডিকেল রিপোর্ট",
      OTHER: "অন্যান্য মেডিকেল ডকুমেন্ট"
    }
  }
};

export const COMMON_DISEASES = [
  { id: 'gastric', label: { en: 'Gastric/Acidity', bn: 'গ্যাস্ট্রিক/এসিডিটি' }, icon: Flame, color: 'text-orange-500', bg: 'bg-orange-50' },
  { id: 'fever', label: { en: 'Fever/Cold', bn: 'জ্বর/ঠান্ডা' }, icon: Thermometer, color: 'text-red-500', bg: 'bg-red-50' },
  { id: 'pain', label: { en: 'Pain/Headache', bn: 'ব্যথা/মাথাব্যথা' }, icon: Zap, color: 'text-yellow-500', bg: 'bg-yellow-50' },
  { id: 'diabetes', label: { en: 'Diabetes', bn: 'ডায়াবেটিস' }, icon: Activity, color: 'text-blue-500', bg: 'bg-blue-50' },
  { id: 'heart', label: { en: 'Heart/Pressure', bn: 'হার্ট/প্রেসার' }, icon: Heart, color: 'text-rose-500', bg: 'bg-rose-50' },
  { id: 'kidney', label: { en: 'Kidney/Urine', bn: 'কিডনি/প্রস্রাব' }, icon: Droplets, color: 'text-sky-500', bg: 'bg-sky-50' },
  { id: 'asthma', label: { en: 'Asthma', bn: 'হাঁপানি/শ্বাসকষ্ট' }, icon: Wind, color: 'text-cyan-500', bg: 'bg-cyan-50' },
  { id: 'cancer', label: { en: 'Cancer', bn: 'ক্যান্সার' }, icon: Dna, color: 'text-slate-500', bg: 'bg-slate-50' },
  { id: 'skin', label: { en: 'Skin/Allergy', bn: 'চামড়া/এলার্জি' }, icon: Sun, color: 'text-amber-500', bg: 'bg-amber-50' },
  { id: 'eye', label: { en: 'Eye Problem', bn: 'চোখের সমস্যা' }, icon: Eye, color: 'text-emerald-500', bg: 'bg-emerald-50' },
  { id: 'dental', label: { en: 'Dental/Teeth', bn: 'দাঁতের সমস্যা' }, icon: Smile, color: 'text-indigo-500', bg: 'bg-indigo-50' },
  { id: 'bone', label: { en: 'Bone/Joints', bn: 'হাড়/বাত' }, icon: Bone, color: 'text-stone-500', bg: 'bg-stone-50' },
  { id: 'vomiting', label: { en: 'Vomiting', bn: 'বমি' }, icon: Pill, color: 'text-teal-500', bg: 'bg-teal-50' },
  { id: 'child', label: { en: 'Child Care', bn: 'শিশুর যত্ন' }, icon: Baby, color: 'text-pink-500', bg: 'bg-pink-50' },
  { id: 'mental', label: { en: 'Mental Health', bn: 'মানসিক স্বাস্থ্য' }, icon: Brain, color: 'text-violet-500', bg: 'bg-violet-50' },
];

export const MOCK_DELAY = 1500;